train_file:  ['/net/acadia10a/data/zkhan/coco-in-albef-format/train2017.json']
val_file: '/net/acadia10a/data/zkhan/flickr30k/flickr30-test-pairs.json' 
test_file: '/net/acadia10a/data/zkhan/flickr30k/flickr30-test-pairs.json'
image_root: '/net/acadia10a/data/zkhan/flickr30k/flickr30k-images'  
save_sims: '/net/acadia10a/data/zkhan/albef-sims'

bert_config: 'configs/dual_stream_ablations/9t_3mm_bert.json'

image_res: 384
batch_size_train: 32
batch_size_test: 64

queue_size: 65536
momentum: 0.995
vision_width: 768
embed_dim: 256
temp: 0.07
k_test: 128

alpha: 0.4
distill: True
warm_up: True

optimizer: {opt: adamW, lr: 1e-5, weight_decay: 0.02} 
schedular: {sched: cosine, lr: 1e-5, epochs: 10, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







